#!/usr/bin/env python3
"""
Export XGBoost model JSON to JavaScript module for MUAD'DIB runtime.

Converts the tree dump from train-classifier.py into a compact JS format
that can be traversed by src/ml/classifier.js without any Python dependency.

Usage:
    python tools/export-model-js.py model.json [--output src/ml/model-trees.js]

Output format:
    module.exports = {
      version: 1,
      features: ['score', 'count_total', ...],
      threshold: 0.45,
      trees: [
        [{f: 0, t: 25.5, y: 1, n: 2, v: 0}, ...],  // tree 0
        [{f: -1, t: 0, y: 0, n: 0, v: 0.123}, ...],  // tree 1 (leaf)
        ...
      ]
    };

Node format:
    f: feature index (-1 for leaf nodes)
    t: split threshold (0 for leaves)
    y: yes (left) child index
    n: no (right) child index
    v: leaf value (0 for internal nodes)
"""

import argparse
import json
import sys
from pathlib import Path


def convert_tree(tree_json: dict, nodes: list, feature_map: dict) -> int:
    """
    Recursively convert an XGBoost tree JSON node to flat array format.
    Returns the index of this node in the nodes array.
    """
    idx = len(nodes)
    nodes.append(None)  # Placeholder

    if 'leaf' in tree_json:
        # Leaf node
        nodes[idx] = {
            'f': -1,
            't': 0,
            'y': 0,
            'n': 0,
            'v': round(tree_json['leaf'], 6)
        }
    else:
        # Internal node
        split_feature = tree_json.get('split', '')
        feature_idx = feature_map.get(split_feature, -1)
        threshold = tree_json.get('split_condition', 0)

        # Process children
        children = tree_json.get('children', [])
        yes_child = tree_json.get('yes', 0)
        no_child = tree_json.get('no', 0)

        # Find yes/no children
        yes_tree = None
        no_tree = None
        for child in children:
            if child.get('nodeid') == yes_child:
                yes_tree = child
            elif child.get('nodeid') == no_child:
                no_tree = child

        # Fallback: if yes/no not matched by nodeid, use order
        if yes_tree is None and len(children) > 0:
            yes_tree = children[0]
        if no_tree is None and len(children) > 1:
            no_tree = children[1]

        # Recurse
        yes_idx = convert_tree(yes_tree, nodes, feature_map) if yes_tree else idx
        no_idx = convert_tree(no_tree, nodes, feature_map) if no_tree else idx

        nodes[idx] = {
            'f': feature_idx,
            't': round(threshold, 6),
            'y': yes_idx,
            'n': no_idx,
            'v': 0
        }

    return idx


def export_to_js(model_path: str, output_path: str):
    """Convert model JSON to JavaScript module."""
    with open(model_path, 'r', encoding='utf-8') as f:
        model = json.load(f)

    features = model['features']
    threshold = model['threshold']
    trees_raw = model['trees_raw']

    # Build feature name -> index mapping
    feature_map = {name: idx for idx, name in enumerate(features)}

    # Convert each tree
    js_trees = []
    for tree_json in trees_raw:
        nodes = []
        convert_tree(tree_json, nodes, feature_map)
        js_trees.append(nodes)

    # Build JS output
    js_model = {
        'version': 1,
        'features': features,
        'threshold': threshold,
        'trees': js_trees
    }

    # Write as JS module with compact tree formatting
    js_content = "'use strict';\n\n"
    js_content += "/**\n"
    js_content += " * XGBoost model trees — auto-generated by tools/export-model-js.py\n"
    js_content += f" * {len(js_trees)} trees, {len(features)} features, threshold={threshold}\n"
    js_content += " * DO NOT EDIT MANUALLY\n"
    js_content += " */\n\n"
    js_content += f"module.exports = {json.dumps(js_model, separators=(',', ':'))};\n"

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(js_content)

    size_kb = Path(output_path).stat().st_size / 1024
    print(f"Exported {len(js_trees)} trees, {len(features)} features to {output_path} ({size_kb:.1f} KB)")
    print(f"Threshold: {threshold}")

    # Verify roundtrip
    total_nodes = sum(len(t) for t in js_trees)
    print(f"Total nodes: {total_nodes}")


def main():
    parser = argparse.ArgumentParser(
        description='Export XGBoost model to JavaScript module')
    parser.add_argument('model', help='Path to model.json from train-classifier.py')
    parser.add_argument('--output', default='src/ml/model-trees.js',
                        help='Output JS file path')
    args = parser.parse_args()

    if not Path(args.model).exists():
        print(f"ERROR: Model file not found: {args.model}", file=sys.stderr)
        sys.exit(1)

    export_to_js(args.model, args.output)
    print(f"\nDone! The model is ready for use in src/ml/classifier.js")


if __name__ == '__main__':
    main()
