'use strict';

/**
 * XGBoost model trees — auto-generated by tools/export-model-js.py
 *
 * Format: { version, features: [...], threshold, trees: [[{f, t, y, n, v}, ...], ...] }
 * Each node: f = feature index (-1 = leaf), t = split threshold,
 *            y = yes child index, n = no child index, v = leaf value
 *
 * Set to null until a trained model is exported.
 * When null, the classifier operates in bypass mode (graceful degradation).
 */
module.exports = null;
